# Generated by Django 4.2.6 on 2023-11-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('sold', 'sold'), ('Summer', 'Summer'), ('ALHajab', 'ALHajab'), ('classic', 'classic'), ('Black', 'Black'), ('New', 'New'), ('winter', 'winter')], default=1, max_length=100, verbose_name='list:'),
            preserve_default=False,
        ),
    ]
