# Generated by Django 4.2.6 on 2023-11-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_product_options_remove_product_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('winter', 'winter'), ('ALHajab', 'ALHajab'), ('New', 'New'), ('Summer', 'Summer'), ('sold', 'sold'), ('classic', 'classic'), ('Black', 'Black')], max_length=100, verbose_name='list:'),
        ),
    ]
