# Generated by Django 4.2.6 on 2023-11-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_product_id_alter_product_listt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('Black', 'Black'), ('ALHajab', 'ALHajab'), ('Summer', 'Summer'), ('New', 'New'), ('sold', 'sold'), ('classic', 'classic'), ('winter', 'winter')], max_length=100, verbose_name='list:'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(max_length=500, verbose_name='Name customer')),
                ('Note', models.TextField(verbose_name=' Note')),
                ('length', models.IntegerField(verbose_name='Abaya length')),
                ('shoulders', models.IntegerField(verbose_name='Abaya shoulders')),
                ('sleeve', models.IntegerField(verbose_name='Abaya sleeves')),
                ('width', models.IntegerField(verbose_name='Abaya width')),
                ('area', models.CharField(max_length=500, verbose_name='Area')),
                ('type_address', models.CharField(choices=[('office', 'office'), ('Home', 'Home'), ('Apartment', 'Apartment')], max_length=100, verbose_name='type_address:')),
                ('block', models.CharField(max_length=500, verbose_name='Block')),
                ('street', models.CharField(max_length=500, verbose_name='street')),
                ('house', models.CharField(max_length=500, verbose_name='house')),
                ('name_prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='Name Product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
    ]
