# Generated by Django 4.2.6 on 2023-11-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_product_listt_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('office', 'office'), ('Apartment', 'Apartment'), ('Home', 'Home')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('classic', 'classic'), ('ALHajab', 'ALHajab'), ('sold', 'sold'), ('Black', 'Black'), ('New', 'New'), ('winter', 'winter'), ('Summer', 'Summer')], max_length=100, verbose_name='list:'),
        ),
    ]
