# Generated by Django 4.2.6 on 2023-11-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_order_payment_alter_order_type_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('Home', 'Home'), ('office', 'office'), ('Apartment', 'Apartment')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('Black', 'Black'), ('classic', 'classic'), ('Summer', 'Summer'), ('winter', 'winter'), ('ALHajab', 'ALHajab'), ('New', 'New'), ('sold', 'sold')], max_length=100, verbose_name='list:'),
        ),
    ]
