# Generated by Django 4.2.6 on 2023-11-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_order_id_alter_product_listt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Phone',
            field=models.CharField(default=1, max_length=500, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Home', 'Home'), ('office', 'office')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('ALHajab', 'ALHajab'), ('Black', 'Black'), ('sold', 'sold'), ('winter', 'winter'), ('Summer', 'Summer'), ('New', 'New'), ('classic', 'classic')], max_length=100, verbose_name='list:'),
        ),
    ]
