# Generated by Django 4.2.6 on 2023-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_about_alter_product_listt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'about', 'verbose_name_plural': 'about'},
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('office', 'office'), ('Home', 'Home')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('ALHajab', 'ALHajab'), ('Summer', 'Summer'), ('sold', 'sold'), ('winter', 'winter'), ('New', 'New'), ('classic', 'classic'), ('Black', 'Black')], max_length=100, verbose_name='list:'),
        ),
    ]
