# Generated by Django 4.2.6 on 2023-11-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_about_options_alter_order_type_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'معلومات الصفحة الرئيسية', 'verbose_name_plural': 'معلومات الصفحة الرئيسية'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'الطلبات', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'المنتجات', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_image_3',
        ),
        migrations.AlterField(
            model_name='order',
            name='Note',
            field=models.TextField(null=True, verbose_name=' ملاحظات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Phone',
            field=models.CharField(max_length=500, verbose_name='رقم جوال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='length',
            field=models.IntegerField(verbose_name='طول العباية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_customer',
            field=models.CharField(max_length=500, verbose_name='اسم الزبون'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_prod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='اسم القطعة المطلوبة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shoulders',
            field=models.IntegerField(verbose_name='أكتاف العباية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sleeve',
            field=models.IntegerField(verbose_name='أكمام العباية '),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('office', 'office'), ('Apartment', 'Apartment'), ('Home', 'Home')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width',
            field=models.IntegerField(verbose_name='صدر العباية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDiscountPrice',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='خصم على هذه القطعة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.FloatField(blank=True, default=1, verbose_name='سعر المنتج'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_image_1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/imgs/product_imgs/', verbose_name='صورة2 لنفس المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_image_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/imgs/product_imgs/', verbose_name='صورة 3 لنفس المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('classic', 'عصري(كلاسيكي)'), ('ALHajab', 'ALHajab'), ('winter', 'قطع شتوية'), ('discount', 'خصومات'), ('Summer', 'قطع صيفية'), ('New', 'جديد'), ('Black', 'أسود')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(verbose_name=' مواصفات المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='products/product.jpg', max_length=500, upload_to='products/imgs/', verbose_name='صورة رئيسية للمنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=150, verbose_name='اسم المنتج'),
        ),
    ]
