# Generated by Django 4.2.6 on 2023-11-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_about_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=500, verbose_name='Area')),
                ('type_address', models.CharField(choices=[('Apartment', 'Apartment'), ('Home', 'Home'), ('office', 'office')], max_length=100, verbose_name='type_address:')),
                ('block', models.CharField(max_length=500, verbose_name='Block')),
                ('street', models.CharField(max_length=500, verbose_name='street')),
                ('house', models.CharField(max_length=500, verbose_name='house')),
                ('payment', models.BooleanField(default=False, verbose_name='payment')),
                ('amount', models.IntegerField(max_length=500, verbose_name='amount')),
            ],
            options={
                'verbose_name': 'الفاتورة',
                'verbose_name_plural': 'الفاتورة',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='area',
        ),
        migrations.RemoveField(
            model_name='order',
            name='block',
        ),
        migrations.RemoveField(
            model_name='order',
            name='house',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_address',
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('discount', 'خصومات'), ('Summer', 'قطع صيفية'), ('winter', 'قطع شتوية'), ('Black', 'أسود'), ('New', 'جديد'), ('classic', 'عصري(كلاسيكي)'), ('ALHajab', 'ALHajab')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
