# Generated by Django 4.2.6 on 2023-11-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_billing_remove_order_area_remove_order_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.billing', verbose_name='billing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.IntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='type_address',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('office', 'office'), ('Home', 'Home')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('winter', 'قطع شتوية'), ('New', 'جديد'), ('Summer', 'قطع صيفية'), ('ALHajab', 'ALHajab'), ('discount', 'خصومات'), ('classic', 'عصري(كلاسيكي)'), ('Black', 'أسود')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
