# Generated by Django 4.2.6 on 2023-11-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_order_billing_alter_billing_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='type_address',
            field=models.CharField(choices=[('Home', 'Home'), ('Apartment', 'Apartment'), ('office', 'office')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('classic', 'عصري(كلاسيكي)'), ('Black', 'أسود'), ('winter', 'قطع شتوية'), ('ALHajab', 'ALHajab'), ('discount', 'خصومات'), ('New', 'جديد'), ('Summer', 'قطع صيفية')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
