# Generated by Django 4.2.6 on 2023-11-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_billing_type_address_alter_product_listt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='type_address',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Home', 'Home'), ('office', 'office')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('ALHajab', 'ALHajab'), ('winter', 'قطع شتوية'), ('Summer', 'قطع صيفية'), ('discount', 'خصومات'), ('Black', 'أسود'), ('classic', 'عصري(كلاسيكي)'), ('New', 'جديد')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
