# Generated by Django 4.2.6 on 2023-11-05 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_billing_type_address_alter_product_listt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='type_address',
            field=models.CharField(choices=[('Home', 'Home'), ('office', 'office'), ('Apartment', 'Apartment')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.billing', verbose_name='billing'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('ALHajab', 'ALHajab'), ('classic', 'عصري(كلاسيكي)'), ('New', 'جديد'), ('Summer', 'قطع صيفية'), ('winter', 'قطع شتوية'), ('Black', 'أسود'), ('discount', 'خصومات')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
