# Generated by Django 4.2.6 on 2023-11-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_billing_type_address_alter_order_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='type_address',
            field=models.CharField(choices=[('office', 'office'), ('Apartment', 'Apartment'), ('Home', 'Home')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('ALHajab', 'ALHajab'), ('classic', 'عصري(كلاسيكي)'), ('discount', 'خصومات'), ('New', 'جديد'), ('Black', 'أسود'), ('winter', 'قطع شتوية'), ('Summer', 'قطع صيفية')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
