# Generated by Django 4.2.6 on 2023-11-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_remove_order_billing_order_amount_order_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('Home', 'Home'), ('Apartment', 'Apartment'), ('office', 'office')], max_length=100, verbose_name='type_address:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('Black', 'أسود'), ('New', 'جديد'), ('discount', 'خصومات'), ('winter', 'قطع شتوية'), ('classic', 'عصري(كلاسيكي)'), ('ALHajab', 'ALHajab'), ('Summer', 'قطع صيفية')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
