# Generated by Django 4.2.6 on 2023-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_remove_order_payment_alter_order_type_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.CharField(max_length=500, verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.CharField(max_length=500, verbose_name='المنزل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=500, verbose_name='الشارع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('office', 'مكتب'), ('Home', 'منزل'), ('Apartment', 'بناية')], max_length=100, verbose_name='مكان التسليم:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('ALHajab', 'ALHajab'), ('classic', 'عصري(كلاسيكي)'), ('discount', 'خصومات'), ('Black', 'أسود'), ('Summer', 'قطع صيفية'), ('New', 'جديد'), ('winter', 'قطع شتوية')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
