# Generated by Django 4.2.6 on 2023-11-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_order_area_alter_order_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(verbose_name='السعر المدفوع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='block',
            field=models.CharField(max_length=500, verbose_name='الطابق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('Home', 'منزل'), ('office', 'مكتب'), ('Apartment', 'بناية')], max_length=100, verbose_name='مكان التسليم:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('Black', 'أسود'), ('ALHajab', 'ALHajab'), ('winter', 'قطع شتوية'), ('classic', 'عصري(كلاسيكي)'), ('discount', 'خصومات'), ('Summer', 'قطع صيفية'), ('New', 'جديد')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
