# Generated by Django 4.2.6 on 2023-11-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_order_amount_alter_order_block_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Note',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('Apartment', 'بناية'), ('office', 'مكتب'), ('Home', 'منزل')], max_length=100, verbose_name='مكان التسليم:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('classic', 'عصري(كلاسيكي)'), ('New', 'جديد'), ('winter', 'قطع شتوية'), ('Summer', 'قطع صيفية'), ('ALHajab', 'ALHajab'), ('Black', 'أسود'), ('discount', 'خصومات')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
