# Generated by Django 4.2.6 on 2023-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_remove_product_url_alter_order_type_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('Apartment', 'بناية'), ('office', 'مكتب'), ('Home', 'منزل')], max_length=100, verbose_name='مكان التسليم:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('Black', 'أسود'), ('New', 'جديد'), ('classic', 'عصري(كلاسيكي)'), ('Summer', 'قطع صيفية'), ('winter', 'قطع شتوية'), ('ALHajab', 'ALHajab'), ('discount', 'خصومات')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
