# Generated by Django 5.0.2 on 2024-02-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_remove_about_imgprofile_alter_product_listt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('Apartment', 'بناية'), ('Home', 'منزل'), ('office', 'مكتب')], max_length=100, verbose_name='مكان التسليم:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('ALHajab', 'ALHajab'), ('winter', 'قطع شتوية'), ('classic', 'عصري(كلاسيكي)'), ('Summer', 'قطع صيفية'), ('Black', 'أسود'), ('discount', 'خصومات'), ('New', 'جديد')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
