# Generated by Django 4.2.11 on 2024-03-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_order_type_address_alter_product_listt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default='', max_length=500, verbose_name='جادة'),
        ),
        migrations.AddField(
            model_name='order',
            name='piece',
            field=models.CharField(default='', max_length=500, verbose_name='قطعة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('office', 'مكتب'), ('Home', 'منزل'), ('Apartment', 'بناية')], max_length=100, verbose_name='مكان التسليم:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('discount', 'خصومات'), ('winter', 'قطع شتوية'), ('Black', 'أسود'), ('New', 'جديد'), ('ALHajab', 'ALHajab'), ('Summer', 'قطع صيفية'), ('classic', 'عصري(كلاسيكي)')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
