# Generated by Django 4.2.11 on 2024-03-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_order_district_order_piece_alter_order_type_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('Home', 'منزل'), ('Apartment', 'بناية'), ('office', 'مكتب')], max_length=100, verbose_name='مكان التسليم:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='listt',
            field=models.CharField(choices=[('Summer', 'قطع صيفية'), ('discount', 'خصومات'), ('ALHajab', 'ALHajab'), ('classic', 'عصري(كلاسيكي)'), ('winter', 'قطع شتوية'), ('New', 'جديد'), ('Black', 'أسود')], max_length=100, verbose_name='تصنيف المنتج '),
        ),
    ]
