# Generated by Django 4.2.11 on 2024-03-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_alter_order_type_address_alter_product_listt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم القسم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/imgs/category_imgs/', verbose_name='صورة توضيحية للقسم')),
            ],
            options={
                'verbose_name': 'أقسام العبايات',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='listt',
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('office', 'مكتب'), ('Home', 'منزل'), ('Apartment', 'بناية')], max_length=100, verbose_name='مكان التسليم:'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.category'),
        ),
    ]
