# Generated by Django 4.2.11 on 2024-03-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_category_remove_product_listt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'أقسام العبايات', 'verbose_name_plural': 'أقسام العبايات'},
        ),
    ]
