# Generated by Django 4.2.11 on 2024-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_alter_order_type_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='landing_image',
            field=models.ImageField(null=True, upload_to='products/imgs/', verbose_name='صورة الغلاف في الصفحة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('Apartment', 'بناية'), ('Home', 'منزل'), ('office', 'مكتب')], max_length=100, verbose_name='مكان التسليم:'),
        ),
    ]
