# Generated by Django 4.2.11 on 2024-03-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_about_landing_image_alter_order_type_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='theme_color',
            field=models.CharField(default='#ff4a17', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='type_address',
            field=models.CharField(choices=[('office', 'مكتب'), ('Home', 'منزل'), ('Apartment', 'بناية')], max_length=100, verbose_name='مكان التسليم:'),
        ),
    ]
